/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#fbf9f5",
        "surface-dim": "#dbdad6",
        "surface-bright": "#fbf9f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ef",
        "surface-container": "#efeeea",
        "surface-container-high": "#eae8e4",
        "surface-container-highest": "#e4e2de",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#504442",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f0ed",
        outline: "#827472",
        "outline-variant": "#d3c3c0",
        "surface-tint": "#745853",
        primary: "#271310",
        "on-primary": "#ffffff",
        "primary-container": "#3e2723",
        "on-primary-container": "#ae8d87",
        "inverse-primary": "#e3beb8",
        secondary: "#655d5a",
        "on-secondary": "#ffffff",
        "secondary-container": "#ece0dc",
        "on-secondary-container": "#6b6360",
        tertiary: "#001e05",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00350f",
        "on-tertiary-container": "#5fa364",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdad4",
        "primary-fixed-dim": "#e3beb8",
        "on-primary-fixed": "#2b1613",
        "on-primary-fixed-variant": "#5b403c",
        "secondary-fixed": "#ece0dc",
        "secondary-fixed-dim": "#cfc4c0",
        "on-secondary-fixed": "#201a18",
        "on-secondary-fixed-variant": "#4c4542",
        "tertiary-fixed": "#abf4ac",
        "tertiary-fixed-dim": "#90d792",
        "on-tertiary-fixed": "#002107",
        "on-tertiary-fixed-variant": "#07521d",
        background: "#fbf9f5",
        "on-background": "#1b1c1a",
        "surface-variant": "#e4e2de",
      },
      fontFamily: {
        headline: ["Playfair Display", "serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "0.5rem",
        sm: "1rem",
        md: "1.5rem",
        lg: "2.5rem",
        xl: "4rem",
        gutter: "24px",
      },
    },
  },
  plugins: [],
}
